[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-cache"]

[phases.build]
cmds = ["rm -rf node_modules/.cache && npm run build"]

[start]
cmd = "npx serve -s dist -l $PORT"
