[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --no-cache"]

[phases.build]
cmds = ["rm -rf node_modules/.cache && npm run build"]
env = { "NODE_ENV" = "development" }

[start]
cmd = "npx serve -s dist -l $PORT"
