[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --no-cache"]

[phases.build]
cmds = ["rm -rf node_modules/.cache dist && NODE_ENV=production npm run build"]

[start]
cmd = "npx serve -s dist -l $PORT --no-cache"
