[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps --no-cache && npm run build"

[deploy]
startCommand = "npx serve -s dist -l $PORT"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
